input-physiodir: "/dartfs-hpc/rc/lab/C/CANlab/labdata/projects/spacetop_projects_cue"
input-behdir: "/dartfs-hpc/rc/lab/C/CANlab/labdata/data/spacetop_data/physio/physio03_bids"
output-logdir: "/dartfs-hpc/rc/lab/C/CANlab/labdata/projects/spacetop_projects_cue/scripts/logcenter"
output-savedir: "/dartfs-hpc/rc/lab/C/CANlab/labdata/projects/spacetop_projects_cue/analysis/physio"
metadata: "/dartfs-hpc/rc/lab/C/CANlab/labdata/projects/spacetop_projects_cue/data/spacetop_task-social_run-metadata.csv"
dictchannel: "/dartfs-hpc/rc/lab/C/CANlab/labdata/data/spacetop_data/scripts/spacetop_prep/physio/p01_channel.json"
slurm-id: "${SLURM_ARRAY_TASK_ID}"
slurm-stride: 10
bids-zeropad: 4
bids-task: "task-cue"
event-name: "event_stimuli"
prior-event: "event_expectrating"
later-event: "event_actualrating"
source-samplingrate: 2000
dest-samplingrate: 25
ttl-index: 1
scl-epochstart: -3
scl-epochend: 20
exclude-sub:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
